REM INSERTING into EBA_SPATIAL_DEFAULTS
SET DEFINE OFF;
Insert into EBA_SPATIAL_DEFAULTS (PARAM,VALUE) values ('UNIT_SYSTEM','METRIC');
Insert into EBA_SPATIAL_DEFAULTS (PARAM,VALUE) values ('DEF_COUNTRY','BR');
