prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/administration_menu.sql
@@application/shared_components/navigation/lists/navigation_bar_list.sql
@@application/shared_components/navigation/lists/navigation.sql
@@application/shared_components/files/oraclemapsregionplugin_nonhtml5version_sql.sql
@@application/shared_components/files/eba_spatial_render_xml_xsl.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/license_terms_accepted.sql
@@application/shared_components/security/authorizations/has_http_access.sql
@@application/shared_components/security/app_access_control/test.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/getimage.sql
@@application/shared_components/logic/application_processes/showthumbnail.sql
@@application/shared_components/logic/application_processes/load_default_settings.sql
@@application/shared_components/logic/application_processes/check_requirements.sql
@@application/shared_components/logic/application_processes/trim_all_page_items.sql
@@application/shared_components/logic/application_items/backtopage.sql
@@application/shared_components/logic/application_items/def_country.sql
@@application/shared_components/logic/application_items/def_mapcenter.sql
@@application/shared_components/logic/application_items/def_zoomlevel.sql
@@application/shared_components/logic/application_items/distance_unit.sql
@@application/shared_components/logic/application_items/licenseterms.sql
@@application/shared_components/logic/application_items/oraclemaps_unitsystem.sql
@@application/shared_components/logic/application_items/requirements_met.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/i_accept.sql
@@application/shared_components/user_interface/lovs/lov_addresses.sql
@@application/shared_components/user_interface/lovs/lov_all_countries.sql
@@application/shared_components/user_interface/lovs/lov_aoi.sql
@@application/shared_components/user_interface/lovs/lov_countries.sql
@@application/shared_components/user_interface/lovs/view_options.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/application_express_accounts.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_sampleappfooter.sql
@@application/shared_components/plugins/dynamic_action/com_oracle_apex_oramaps_getcircle.sql
@@application/shared_components/plugins/dynamic_action/com_oracle_apex_elocgeocoder.sql
@@application/shared_components/plugins/dynamic_action/com_oracle_apex_oramaps_getloc.sql
@@application/shared_components/plugins/dynamic_action/com_oracle_apex_oramaps_setcentzo.sql
@@application/shared_components/plugins/dynamic_action/com_oracle_apex_oramaps_getdata.sql
@@application/shared_components/plugins/dynamic_action/com_oracle_apex_oramaps_getredlin.sql
@@application/shared_components/plugins/dynamic_action/com_oracle_apex_oramaps_setmarker.sql
@@application/shared_components/plugins/dynamic_action/com_oracle_apex_oramaps_clearrl.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_oramaps_html5.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00044.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00061.sql
@@application/pages/page_00071.sql
@@application/pages/page_00077.sql
@@application/pages/page_00078.sql
@@application/pages/page_00099.sql
@@application/pages/page_00101.sql
@@application/pages/page_00201.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_create_db_objects.sql
@@application/deployment/install/install_create_geocoder_pl_sql_package.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
