--------------------------------------------------------
--  Constraints for Table EBA_SPATIAL_COUNTRIES
--------------------------------------------------------

  ALTER TABLE "EBA_SPATIAL_COUNTRIES" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "EBA_SPATIAL_COUNTRIES" MODIFY ("COUNTRY_NAME" NOT NULL ENABLE);
  ALTER TABLE "EBA_SPATIAL_COUNTRIES" MODIFY ("GCDR_SUPPORTED" NOT NULL ENABLE);
  ALTER TABLE "EBA_SPATIAL_COUNTRIES" MODIFY ("MAP_CENTERX" NOT NULL ENABLE);
  ALTER TABLE "EBA_SPATIAL_COUNTRIES" MODIFY ("MAP_CENTERY" NOT NULL ENABLE);
  ALTER TABLE "EBA_SPATIAL_COUNTRIES" MODIFY ("MAP_ZOOM" NOT NULL ENABLE);
  ALTER TABLE "EBA_SPATIAL_COUNTRIES" ADD CONSTRAINT "EBA_SPATIAL_GCDRSUPP_CH" CHECK (gcdr_supported in ('Y', 'N')) ENABLE;
  ALTER TABLE "EBA_SPATIAL_COUNTRIES" ADD CONSTRAINT "EBA_SPATIAL_COUNTRIES_PK" PRIMARY KEY ("CODE") USING INDEX  ENABLE;
