--------------------------------------------------------
--  Constraints for Table EBA_SPATIAL_ADDRESSES
--------------------------------------------------------

  ALTER TABLE "EBA_SPATIAL_ADDRESSES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "EBA_SPATIAL_ADDRESSES" MODIFY ("ADDR_NAME" NOT NULL ENABLE);
  ALTER TABLE "EBA_SPATIAL_ADDRESSES" MODIFY ("ADDR_CITY" NOT NULL ENABLE);
  ALTER TABLE "EBA_SPATIAL_ADDRESSES" MODIFY ("ADDR_COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "EBA_SPATIAL_ADDRESSES" MODIFY ("ADDR_TYPE" NOT NULL ENABLE);
  ALTER TABLE "EBA_SPATIAL_ADDRESSES" ADD CONSTRAINT "EBA_SPATIAL_ADDRESSES_TYPE_CK" CHECK (addr_type in ('SUPPLIER', 'CUSTOMER')) ENABLE;
  ALTER TABLE "EBA_SPATIAL_ADDRESSES" ADD CONSTRAINT "EBA_SPATIAL_ADDRESSES_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
